### 1 Numpy

In [2]:
import numpy as np

In [66]:
a = np.array([[1,6], [2,8], [3,11], [3,10] , [1,7]], float)

In [67]:
a

array([[ 1.,  6.],
       [ 2.,  8.],
       [ 3., 11.],
       [ 3., 10.],
       [ 1.,  7.]])

In [43]:
mean_a = []
mean_a.append(a[0: , 0].mean())
mean_a.append(a[0: , 1].mean())
mean_a

[2.0, 8.4]

In [68]:
a_centered = a.copy()
i = 0
while i < len(mean_a):
    j = 0
    while j < len(a_centered[:,i]):
        a_centered[j, i] -= mean_a[i]
        j += 1
    i += 1

In [69]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [75]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:, 1])
a_centered_sp

8.0

In [159]:
cov = a_centered_sp / (len(a) - 1)
cov

2.0

### Проверка

In [156]:
a_t = a.transpose()
a_t

array([[ 1.,  2.,  3.,  3.,  1.],
       [ 6.,  8., 11., 10.,  7.]])

In [157]:
check = np.cov(a_t)
check

array([[1. , 2. ],
       [2. , 4.3]])

In [160]:
cov == check[0, 1]

True

### Pandas

In [80]:
import pandas as pd

In [88]:
a_id =  [1,2,3]
a_name = ['Тургенев', 'Чехов', 'Островский']
authors = pd.DataFrame({'author_id': a_id, 'author_name': a_name})

In [89]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [90]:
book  = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                      'book_title ': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price': [450, 300, 350, 500, 450, 370, 290]})
book

author_id           book_title   price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [98]:
authors_price = pd.merge(authors, book, on= 'author_id', how='inner')
authors_price

author_id author_name           book_title   price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [99]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name        book_title   price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

не понял можно ли было это сделать одной командой...уверен что можно, но что то не додумался как 

In [150]:
max_p = authors_price.groupby('author_name').agg({'price':'max'})
max_p = max_p.rename(columns={'price':'max_price'})
min_p = authors_price.groupby('author_name').agg({'price':'min'})
min_p = min_p.rename(columns={'price':'min_price'})
mean_p = authors_price.groupby('author_name').agg({'price':'mean'})
mean_p = mean_p.rename(columns={'price':'mean_price'})



In [153]:
authors_stat = pd.concat([max_p, min_p, mean_p], axis = 1)

In [154]:
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

In [161]:
authors_price["cover"] =  ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [162]:
authors_price

author_id author_name           book_title   price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [163]:
?pd.pivot_table

In [170]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [175]:
pd.to_pickle(book_info, "./book_info.pkl")

In [178]:
book_info2 = pd.read_pickle("./book_info.pkl")
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [177]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950